#!/usr/bin/env node
// Generates the credits.html attribution section (repo/ only) and THIRD_PARTY_NOTICES.md
// for whichever repo this copy runs in, from data/credits-registry.json.
// Usage: node scripts/gen-credits.mjs <repo-id> [--check]
// repo-id one of: repo | mcp-apps-poc | helm | anchor-suite
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(fileURLToPath(import.meta.url), '..', '..');
const args = process.argv.slice(2);
const repoId = args.find(a => !a.startsWith('--'));
const checkOnly = args.includes('--check');

if (!repoId || !['repo', 'mcp-apps-poc', 'helm', 'anchor-suite'].includes(repoId)) {
  console.error('Usage: node scripts/gen-credits.mjs <repo-id> [--check]  (repo-id: repo|mcp-apps-poc|helm|anchor-suite)');
  process.exit(1);
}

const registryPath = path.join(ROOT, 'data', 'credits-registry.json');
const registry = JSON.parse(readFileSync(registryPath, 'utf8'));

function esc(s) { return String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); }

// ---- THIRD_PARTY_NOTICES.md for this repo ----
function buildNotices() {
  const items = registry.vendored.filter(v => v.repos.includes(repoId));
  const lines = [];
  lines.push('# Third-Party Notices');
  lines.push('');
  lines.push('<!-- GENERATED by scripts/gen-credits.mjs from data/credits-registry.json — do not hand-edit. -->');
  lines.push('');
  lines.push(`Generated ${new Date().toISOString().slice(0, 10) === undefined ? '' : ''}from the shared credits registry (\`data/credits-registry.json\`, source audit: \`${registry.source_audit}\`).`);
  lines.push('');
  if (items.length === 0) {
    lines.push('No third-party vendored code is currently registered for this repo.');
    lines.push('');
    return lines.join('\n');
  }
  for (const it of items) {
    lines.push(`## ${it.name}`);
    lines.push('');
    lines.push(`- **Version:** ${it.version || 'n/a'}`);
    lines.push(`- **License:** ${it.license}`);
    lines.push(`- **Upstream:** ${it.upstream_url || 'n/a'}`);
    const noticeState = it.upstream_ships_notice === true ? 'yes' : it.upstream_ships_notice === false ? 'no (checked upstream root — no NOTICE file)' : 'unresolved — flag separately';
    lines.push(`- **Upstream ships a NOTICE file:** ${noticeState}`);
    if (it.reference_only) lines.push('- **Note:** reference-only citation, not executed at runtime.');
    if (it.note) lines.push(`- **Note:** ${it.note}`);
    const paths = (it.paths && it.paths[repoId]) || [];
    if (paths.length) {
      lines.push(`- **Path(s) in this repo:**`);
      for (const p of paths) lines.push(`  - \`${p}\``);
    }
    if (it.upstream_ships_notice === true && it.notice_text) {
      lines.push('');
      lines.push('**Upstream NOTICE (propagated verbatim, per Apache-2.0 §4(d)):**');
      lines.push('```');
      lines.push(it.notice_text);
      lines.push('```');
    }
    lines.push('');
  }
  return lines.join('\n');
}

// ---- credits.html generated section (repo/ only) ----
const MARK_START = '<!--CREDITS-GENERATED:START (generated by scripts/gen-credits.mjs from data/credits-registry.json — do not hand-edit)-->';
const MARK_END = '<!--CREDITS-GENERATED:END-->';

function buildCreditsSection() {
  const out = [];
  out.push(MARK_START);
  for (const p of registry.pattern_only) {
    const statusClass = p.status === 'live' ? 'status-live' : 'status-specced';
    const statusLabel = p.status === 'live' ? 'Live' : 'Specced, not yet shipped';
    out.push('    <div class="credit-card">');
    out.push('      <div class="credit-head">');
    out.push(`        <span class="credit-name">${p.name}</span>`);
    out.push(`        <span class="credit-status ${statusClass}">${statusLabel}</span>`);
    out.push(`        <span class="credit-license">${esc(p.license)}</span>`);
    out.push('      </div>');
    out.push(`      <p class="credit-desc">${p.desc}</p>`);
    out.push(`      <p class="credit-used"><strong>Used in:</strong> ${p.used_in_html}${p.upstream_url ? ` <a href="${p.upstream_url}" target="_blank" rel="noopener noreferrer">${p.upstream_url.replace('https://', '')} ↗</a>` : ''}</p>`);
    out.push('    </div>');
    out.push('');
  }
  // Vendored code (this repo's slice) — acknowledgment card, licence detail lives in THIRD_PARTY_NOTICES.md
  const vendored = registry.vendored.filter(v => v.repos.includes('repo'));
  if (vendored.length) {
    out.push('    <div class="credit-card">');
    out.push('      <div class="credit-head">');
    out.push('        <span class="credit-name">Vendored open-source code</span>');
    out.push('        <span class="credit-status status-live">Live</span>');
    out.push('        <span class="credit-license">Various (see THIRD_PARTY_NOTICES.md)</span>');
    out.push('      </div>');
    out.push(`      <p class="credit-desc">Runtime dependencies bundled directly into kernel code: ${vendored.map(v => esc(v.name)).join(', ')}. Full per-item license and path detail is generated into <a href="THIRD_PARTY_NOTICES.md" target="_blank">THIRD_PARTY_NOTICES.md</a>, not duplicated here.</p>`);
    out.push('      <p class="credit-used"><strong>Used in:</strong> kernel bundles across the ChainGraph standard library.</p>');
    out.push('    </div>');
    out.push('');
  }
  out.push(MARK_END);
  return out.join('\n');
}

function writeIfChanged(filePath, content, label) {
  const existing = existsSync(filePath) ? readFileSync(filePath, 'utf8') : null;
  if (existing === content) return { changed: false };
  if (checkOnly) {
    console.error(`STALE: ${label} does not match generator output. Run without --check to regenerate.`);
    return { changed: true, stale: true };
  }
  writeFileSync(filePath, content);
  console.log(`wrote ${label}`);
  return { changed: true };
}

let staleFound = false;

const noticesPath = path.join(ROOT, 'THIRD_PARTY_NOTICES.md');
const noticesResult = writeIfChanged(noticesPath, buildNotices(), 'THIRD_PARTY_NOTICES.md');
if (noticesResult.stale) staleFound = true;

if (repoId === 'repo') {
  const creditsPath = path.join(ROOT, 'credits.html');
  const html = readFileSync(creditsPath, 'utf8');
  const startIdx = html.indexOf(MARK_START);
  const endIdx = html.indexOf(MARK_END);
  if (startIdx === -1 || endIdx === -1) {
    console.error('credits.html is missing CREDITS-GENERATED markers — cannot regenerate. Add markers around the attribution ledger cards first.');
    process.exit(1);
  }
  const newSection = buildCreditsSection();
  const newHtml = html.slice(0, startIdx) + newSection + html.slice(endIdx + MARK_END.length);
  const result = writeIfChanged(creditsPath, newHtml, 'credits.html');
  if (result.stale) staleFound = true;
}

if (checkOnly) {
  if (staleFound) process.exit(1);
  console.log(`gen-credits.mjs --check ${repoId}: clean`);
  process.exit(0);
}
